language: shell

cache:
  directories:
    - "$HOME/.cargo"
before_cache:
  - cargo install -Z install-upgrade cargo-cache --debug
  - cargo cache --autoclean

before_install:
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly --profile=minimal
  - export PATH="$HOME/.cargo/bin:$PATH"

install:
  - cargo install -Z install-upgrade mdbook

script:
  - mdbook test
