language: shell

cache: cargo

before_install:
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly --profile=minimal
  - export PATH="$HOME/.cargo/bin:$PATH"

before_script:
  - (cargo install mdbook --force || true)

script:
  - mdbook test
